apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejemplo-microservice-deployment
  labels:
    app: ejemplo-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ejemplo-microservice
  template:
    metadata:
      labels:
        app: ejemplo-microservice
    spec:
      containers:
      - name: microservice
        image: ejemplo-microservice:0.1.0 # usamos nuestra imagen construida previamente
        ports:
        - containerPort: 80
        livenessProbe: # para verificar si la aplicación está viva
          httpGet:
            path: /api/items/
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe: # para verificar si la aplicación está lista para recibir tráfico
          httpGet:
            path: /api/items/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1
